sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: vanssupremezack1
    type: com.alibaba.druid.pool.DruidDataSource
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tRH2fejVHT5yeuBxEP1
    access-key-secret: XNDg4ds3lHrwMn6kXfiKLeMFVSKUaO
    bucket-name: hushleadnews
  data:
    redis:
      host: localhost
      port: 6379
      password: vanssupremezack1
      database: 0

